project:
  type: website

execute:
  # Point to the R environment under website
  # renv-path: website/renv
  renv-path: renv
  
website:
  title: "CAP-6771 - Data-Mining Project (Fall-2025)"
  navbar:
    tools:
      - icon: github
        href: https://github.com/renanmb/
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Project
      - href: blog.qmd
        text: Blog
      # - href: about.qmd
      #   text: About Us
      - href: people/index.qmd
        text: About Us

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # light: [flatly, theme.scss]
      # dark: [flatly, theme-dark.scss]
    css: styles.css
    toc: true

# csl: national-library-of-medicine.csl 
csl: apa-numeric-superscript-brackets.csl 


